config/routes.rb
Rails.application.routes.draw do
  resources :morning_pages do
    collection do
      get :archive
    end
  end
  resources :tasks do
    member do
      get :change_status
    end
  end
  devise_for :users
  get "home/index"
  get "completed" => "home#completed"
  get "help" => "home#help"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 3 }
  validates :status, presence: true
  enum :status, [ :doing, :backlog, :idea, :done ]

  after_initialize :set_default_status, if: :new_record?

  def set_default_status
    self.status ||= :backlog
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: %i[ show edit update destroy change_status ]

  # GET /tasks or /tasks.json
  # # Here for posperity sake, we will not be using this method
  # # Instead we will be using the home controller to display the tasks
  def index
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  def change_status
    if Task.statuses.keys.include?(params[:status])
      @task.update(status: params[:status])
      redirect_to home_index_path, notice: "Task status was successfully updated."
    else
      redirect_to home_index_path, alert: "Invalid status."
    end
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    @task.user = current_user

    prefered_status_on_creation(@task)

    respond_to do |format|
      if @task.save
        format.html { redirect_to home_index_path, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # This method is used to set the status of the task
  # based on the last occurence of @doing or @idea in the title
  # We allow users to pass in the status as a parameter in the title aka. @doing or @idea
  def prefered_status_on_creation(task)
    pattern = /@doing|@idea/
    last_occurrence = @task.title.match(pattern).to_s

    status_map = { "@doing" => "doing", "@idea" => "idea" }

    if last_occurrence.present?
      @task.status = status_map[last_occurrence]
      @task.title = @task.title.reverse.sub(last_occurrence.reverse, "").reverse
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      @task.user = current_user
      if @task.update(task_params)
        format.html { redirect_to edit_task_path(@task), notice: "Task was successfully updated." }
        format.json { render json: { success: true }, status: :ok }
      else
        format.html { render :edit, status: :unprocessable_entity }
        render json: { success: false, errors: @task.errors.full_messages }, status: :unprocessable_entity
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy!

    respond_to do |format|
      format.html { redirect_to root_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :status, :user_id)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with model: @task, remote: true, class: "flex-1 flex flex-col", html: { data: { controller: "savetask" } } do |f| %>
  <!-- Placeholder for the error message -->
  <div class="my-4 p-2 bg-red-300" data-savetask-target="error" style="display: none;">
    An error occurred while saving. Please try again.
  </div>

  <!-- Main Content Area -->
  <div class="flex-1 py-2 flex flex-col h-full">
    <%= f.text_area :title, 
      data: { action: "input->savetask#debouncedSave", savetask_target: "content" }, 
      class: "flex-1 w-full resize-none border rounded p-2" 
    %>
  </div>

  <!-- Footer (Sticky with 2 Rows) -->
  <footer class="bg-gray-100 py-2 w-full">
    <div class="flex flex-col md:flex-row gap-4 mb-4 bg-blue-100 p-4">
      <div class="w-full md:w-3/4 rounded md:text-sm">
        <div class="grid sm:grid-cols-4 gap-3">
          <% Task.statuses.each do |key, value| %>
            <% id = "task_status_#{key}" %>
            <label for="<%= id %>" class="relative flex flex-col bg-white p-4 pb-1 rounded-lg shadow-md cursor-pointer">
              <span class="font-semibold text-gray-500 leading-tight uppercase mb-3"><%= key.humanize %></span>
              <%= f.radio_button :status, key, id: id, 
                data: { action: "savetask#save", savetask_target: "status" }, 
                class: "absolute h-0 w-0 appearance-none sr-only" 
              %>
              <span aria-hidden="true" class="hidden absolute inset-0 border-2 border-green-500 bg-green-200 bg-opacity-10 rounded-lg">
                <span class="absolute top-3 right-4 h-6 w-6 inline-flex items-center justify-center rounded-full bg-green-200">
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="h-5 w-5 text-green-600">
                    <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd" />
                  </svg>
                </span>
              </span>
            </label>
        <% end %>
        </div>

      </div>

      <div class="w-full md:w-1/4 p-4 rounded">
        <div id="autosave-status" class="text-gray-500 transition-opacity duration-1000">&nbsp;</div>
      </div>
    </div>

    <div class="flex ">
      <div class="w-1/2 py-4">
        <%= link_to "Delete", task_path(task), 
          data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
          class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" %> 
      </div>
      
      <div class="w-1/2 pt-4 text-end">
        <%= link_to "Back to tasks", root_path, 
          class: "ms-4 text-base font-bold text-blue-600 hover:text-gray-900" %>
      </div>
    </div>
    
  </footer>
<% end %>

app/views/tasks/_short_form.html.erb
<%= form_with model: @task, class: "mb-4 w-full" do |form| %>
<%= form.label :title, class: "sr-only" %>
<%= form.text_field :title, data: { controller: "focus" }, class: "w-full p-2 border border-gray-300 rounded-lg focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500", placeholder: "Add a new task" %>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>Title:</strong>
    <%= task.title %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= task.status %>
  </p>

  <p>
    <strong>User:</strong>
    <%= task.user_id %>
  </p>

</div>

app/views/tasks/_task_item.html.erb
<div id="<%= dom_id task %>">
    <% maxLength = 40 %>
    <% ellipsis = '...' %>
    <%# Next in Line %>
    <p class="text-base font-bold text-blue-600 mb-1">
          <a data-id="<%= task.id %>" href="<%= edit_task_path(task) %>" class="hover:text-gray-900">
          <% title_lines = task.title.split("\n") %>
          <% first_line = title_lines[0] %>
          <% truncated_line = first_line.length > maxLength ? first_line.truncate(maxLength, separator: ' ') : first_line %>
          <%= truncated_line %>
          <%= ' +' if title_lines.length > 1 %>
        </a>
      <br/>

      <%# Action Links %>
      <% statuses = Task.statuses.keys - [task.status] %>
      <% statuses.each_with_index do |status, index| %>
        <%= link_to status.humanize, change_status_task_path(task, status: status), method: :patch, class: "hover:underline text-xs text-gray-500 space-x-1" %>
        <%= ' - ' unless index == statuses.size - 1 %>
      <% end %>
    </p>
</div>

app/views/tasks/edit.html.erb
  
  <% content_for :title, "Editing task" %>

  <%= render "form", task: @task %>

app/views/tasks/index.html.erb
<% content_for :title, "Tasks" %>

<h1>Tasks</h1>

<div id="tasks">
  <% @tasks.each do |task| %>
    <%= render task %>
    <p>
      <%= link_to "Show this task", task %>
    </p>
  <% end %>
</div>

<%= link_to "New task", new_task_path %>

app/views/tasks/new.html.erb
<% content_for :title, "New task" %>

<h1>New task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Back to tasks", tasks_path %>
</div>
<br>

app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @task %>

<div>
  <%= link_to "Edit this task", edit_task_path(@task) %> |
  <%= link_to "Back to tasks", tasks_path %>

  <%= button_to "Destroy this task", @task, method: :delete %>
</div>