config/routes.rb
Rails.application.routes.draw do
  resources :morning_pages do
    collection do
      get :archive
    end
  end
  resources :tasks do
    member do
      get :change_status
    end
  end
  devise_for :users
  get "home/index"
  get "completed" => "home#completed"
  get "help" => "home#help"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_layout

  def index
    @task = Task.new
    @doing = Task.where(status: :doing).where(user: current_user)
    @backlog = Task.where(status: :backlog).where(user: current_user)
    @ideas = Task.where(status: :idea).where(user: current_user)
  end

  def completed
    @pagy, @completed_tasks = pagy(Task.where(status: "done").where(user: current_user.id).order(created_at: :desc))
  end

  def help
  end

  private

  def set_layout
    if user_signed_in?
      self.class.layout "application"
    else
      self.class.layout "application"
    end
  end

  def user_signed_in?
    current_user.present?
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_home-page.html.erb
<!-- HERO SECTION -->


  <div class="grid grid-cols-1 lg:grid-cols-6 gap-4">

    <!-- Top Row, First Column (3/4 width) -->
    <div class="order-2 lg:order-1 lg:col-span-4">

        <div class="font-serif">
            <!-- Content for the first column -->
            <h1 class="text-5xl font-bold md:my-6">SixTasks&trade;</h1>
            <h4 class="text-2xl md:text-3xl text-gray-700">
                The SixTasks™ helps you to focus on what matters most. 
                It offers a dedicated space for tasks, writing and note-taking, along with 
                a tool to cultivate good habits.
            </h4>
            <p class="mt-3 text-base/7 font-bold">
                But foremost, it is designed to help you to stay focused on whats most important.
            </p>
            <p class="mt-3 text-base/7 mt-8">
                Take it from Margareth Theatcher:
            </p>
            <blockquote class="mt-3 p-4 border-l-4 border-blue-500 bg-blue-50 text-lg italic text-gray-700 rounded-md shadow-md">
            "Plan your work for today and every day, then work your plan."
            </blockquote>
        </div>
        
    </div>

    <!-- Top Row, Second Column (1/4 width) -->
    <div class="order-1 lg:order-2 lg:col-span-2">
      <div class="p-4 bg-white shadow-lg rounded-md shadow-lg text-center font-bold">
        <!-- Content for the second column -->
        <h3 class="text-2xl font-bold text-center">Get Started</h3>
        <p class="text-base md:text-1xl my-5">
            Do important stuff<br/>
            <span class="text-green-700 text-sm">SixTasks&trade;</span>
        </p>
        <p class="text-base mt:text-4xl my-5">
            Write epic things<br/>
            <span class="text-green-700 text-sm">Pages</span>
        </p>
        <p class="text-base mt:text-4xl my-5">
            Acquire (good) habits<br/>
            <span class="text-green-700 text-sm">Habits</span>
        </p>
        <p class="text-base font-light font-serif m-8">
            All included.
        </p>
        <a href="/users/sign_up" class="block bg-green-500 hover:bg-green-700 text-white font-bold py-4 px-8 rounded w-full">
            Get Started
        </a>
      </div>
    </div>

    <%# COMMENTED OUT FOR NOW
    <!-- Second Row, Full Width Column -->
    <div class="order-3 lg:order-3 col-span-1 lg:col-span-6">
      <div class="p-4 bg-white shadow-lg rounded-md">
        <!-- Content for the full width column -->
        <h2 class="text-2xl font-bold">Full Width Content</h2>
        <p class="mt-2 text-gray-600">This is the full width content area.</p>
      </div>
    </div> %>
  </div>

app/views/home/completed.html.erb
<%= render "tasks/short_form" %>

<h1 class="text-3xl font-bold mb-6">Completed</h1>

<div class="space-y-4">

<% if @completed_tasks.present? %>
    <% @completed_tasks.each do |completed| %>
        <%= render "tasks/task_item", task: completed %>
    <% end %>
    <%== pagy_nav(@pagy) %>
<% else %>
        <p>Nothing yet.</p>
<% end %>

</div>

app/views/home/help.html.erb
<h1>Help</h1>

<ul>
    <li>There is a small dash at the end of my task?</li>
</ul>

<div id="">
    <h2>There is a small dash at the end of my task?</h2>
    <p>That is a feature of the app. It is a visual cue to let you know there is more to the task than shown.</p>
</div>

app/views/home/index.html.erb
    <% if current_user.present? %>

        <%= render "tasks/short_form" %>

        <!-- Doing Section -->
        <div class="lg:my-2 text-xl font-bold text-orange-600 mb-2 lg:block">Doing</div>
        <div class="p-2">
            <% if @doing.present? %>
                <% @doing.each do |doing| %>
                    <%= render "tasks/task_item", task: doing %>
                <% end %>
            <% else %>
                Nothing to show yet.
            <% end %>
        </div>

        <!-- Backlog Section -->
        <div class="lg:my-2 text-xl font-bold text-orange-600 mb-2 lg:block">Backlog</div>
        <div class="lg:my-2 p-2">
            <% if @backlog.present? %>
                <% @backlog.each do |backlog| %>
                    <%= render "tasks/task_item", task: backlog %>
                <% end %>
            <% else %>
                Nothing to show yet.
            <% end %>
        </div>

        <!-- Ideas Section -->
        <div class="lg:my-2 text-xl font-bold text-orange-600 mb-2 lg:block">Ideas</div>
        <div class="lg:my-2 p-2">
            <% if @ideas.present? %>
                <% @ideas.each do |idea| %>
                    <%= render "tasks/task_item", task: idea %>
                <% end %>
            <% else %>
                Nothing to show yet.
            <% end %>
        </div>

        <!-- Divider -->
        <div class="border-t border-gray-300 my-4"></div>
        <p class="text-xs text-gray-500 space-x-1"><%= link_to 'Done Tasks', completed_path %></p>

    <% else %>
        
        <%= render "home/home-page" %>
        
    <% end %>