config/routes.rb
Rails.application.routes.draw do
  resources :morning_pages do
    collection do
      get :archive
    end
  end
  resources :tasks do
    member do
      get :change_status
    end
  end
  devise_for :users
  get "home/index"
  get "completed" => "home#completed"
  get "help" => "home#help"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"
end

app/models/morning_page.rb
class MorningPage < ApplicationRecord
  belongs_to :user
  has_rich_text :body # this is for ActionText

  # after_initialize :set_default_body, if: :new_record?
end

app/controllers/morning_pages_controller.rb
class MorningPagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_morning_page, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token


  # GET /morning_pages or /morning_pages.json
  def index
    ensure_morning_page_for_today

    # count the number of words in the morning page
    @word_count = count_words(@morning_page.body)
  end

  # Helper method to count words in the given content
  def count_words(content)
    # Strip HTML tags and count the words
    plain_text = ActionView::Base.full_sanitizer.sanitize(content)
    # Check first if there is any content
    return 0 if plain_text.blank?
    plain_text.split(/\s+/).count
  end

  def archive
    # Find all morning pages for the current user
    @pagy, @morning_pages = pagy(MorningPage.where(user: current_user).order(created_at: :desc))
  end

  # GET /morning_pages/1 or /morning_pages/1.json
  def show
  end

  # GET /morning_pages/new
  def new
    @morning_page = MorningPage.new
  end

  # GET /morning_pages/1/edit
  def edit
  end

  # POST /morning_pages or /morning_pages.json
  # Here for posperity, not used in the app
  def create
    @morning_page = MorningPage.new(morning_page_params)
    @morning_page.user = current_user

    respond_to do |format|
      if @morning_page.save
        format.html { redirect_to morning_page_url(@morning_page), notice: "Morning page was successfully created." }
        format.json { render :show, status: :created, location: @morning_page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @morning_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /morning_pages/1 or /morning_pages/1.json
  def update
    respond_to do |format|
      puts params
      @morning_page.user = current_user
      if @morning_page.update(morning_page_params)
        format.html { redirect_to edit_morning_page_path(@morning_page), notice: "Morning page was successfully updated." }
        format.json { render json: { message: "ok" }, status: :ok }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @morning_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /morning_pages/1 or /morning_pages/1.json
  def destroy
    @morning_page.destroy!

    respond_to do |format|
      format.html { redirect_to morning_pages_url, notice: "Morning page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_morning_page
      @morning_page = MorningPage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def morning_page_params
      params.require(:morning_page).permit(:body, :user_id)
    end

    # Helper method to ensure a morning page exists for the current user and day
    def ensure_morning_page_for_today
      today_range = current_user_time_zone.now.beginning_of_day..current_user_time_zone.now.end_of_day

      # Find the morning page for the current user within the time range
      @morning_page = MorningPage.where(created_at: today_range, user: current_user).first

      # If no morning page is found, create a new one
      unless @morning_page
        @morning_page = MorningPage.create!(created_at: current_user_time_zone.now, user: current_user, body: "a clean slate")
      end
    end

    # Helper method to get the current user's time zone
    def current_user_time_zone
      Time.use_zone(current_user.time_zone) { Time.zone }
    end
end

app/helpers/morning_pages_helper.rb
module MorningPagesHelper
end

app/views/morning_pages/_form.html.erb
<trix-toolbar id="trix-toolbar-1" class="sticky top-0 z-10 bg-gray-50 shadow-md border-b border-gray-300 p-4 pb-1"></trix-toolbar>

<div class="flex-1 flex flex-col overflow-hidden">
  <%= form_with model: @morning_page, remote: true, 
        class: "flex-1 flex flex-col overflow-hidden", html: { data: { controller: "savepage word-count" } } do |f| %>
    
    <!-- Span fixed to the bottom right corner, desktop only. Shows the wordcount -->
    <span class="hidden lg:block fixed bottom-16 right-10 m-4 bg-lime-100 text-gray-500 py-2 px-4 rounded">
      <span id="word-count" class="text-gray-700" data-word-count-target="wordCount"><%= @word_count %> words</span>
    </span>

        <!-- Placeholder for the error message -->
    <div class="my-4 p-2 bg-red-300" data-savepage-target="error" style="display: none;">
      An error occurred while saving. Please try again.
    </div>

    <!-- Textarea (or Trix Editor) -->
    <div class="flex-1 p-4 overflow-hidden">
      <%= f.rich_text_area :body,
        toolbar: "trix-toolbar-1",
        class: "w-full h-full p-2 ", 
        data: { action: "input->savepage#debouncedSave", savepage_target: "content", word_count_target: "content" },  
        style: "border: none;"
      %>
    </div>
  <% end %>
</div>

    <!-- Footer (Sticky with 2 Rows) -->
    <footer class="bg-gray-100 py-4 w-full">

      <div class="flex ">
        <div class="w-1/2 py-4">
          <%= link_to "Archive", archive_morning_pages_path, 
            class: "bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded" %>
        </div>

        <div class="w-1/4 py-4">
          <div id="autosave-status" class="text-gray-500 transition-opacity duration-1000">&nbsp;</div>
        </div>
        
        <div class="w-1/4 pt-4 text-end">
          <%= link_to "Back to tasks", root_path, 
            class: "ms-4 text-base font-bold text-blue-600 hover:text-gray-900" %>
        </div>
      </div>
      
    </footer>
  

<script>
  document.addEventListener("trix-initialize", function(event) {
  const toolbar = document.getElementById("trix-toolbar-1");
  if (toolbar) {
    event.target.toolbarElement = toolbar;
  }
});
</script>

app/views/morning_pages/_morning_page.html.erb
<div class="m-4" id="<%= dom_id morning_page %>">
    <p class="my-3 font-semibold text-lg border-b-2 border-gray-300 pb-2">
    Created: <%= morning_page.created_at.strftime("%A, %B %d, %Y") %>
  </p>
  <%= morning_page.body %>
</div>

app/views/morning_pages/archive.html.erb
<%= render "tasks/short_form" %>

<h1 class="text-3xl font-bold mb-6">Past entries</h1>

<div class="space-y-4">

  <% @morning_pages.each do |morning_page| %>
    <div class="py-2 px-4 bg-white shadow rounded-lg">
      <h2 class="text-xl font-semibold text-gray-800"><%= morning_page.created_at.strftime("%A, %B %d, %Y") %></h2>
      <!-- If there is body content, display the first line or else display a message -->
      <p class="text-gray-600 mt-1">
        <% if morning_page.body.present? %>
          <%= link_to first_line_of_trix_content(morning_page.body, 30), morning_page_path(morning_page), class: "text-blue-500 hover:underline" %>
        <% else %>
          No content created that day
        <% end %>
      </p>
    </div>
  <% end %>

  <div class="mt-4">
    <%== pagy_nav(@pagy) %>
  </div>

</div>

app/views/morning_pages/edit.html.erb
<% content_for :title, "Editing morning page" %>

<h1>Editing morning page</h1>

<%= render "form", morning_page: @morning_page %>

<br>

<div>
  <%= link_to "Show this morning page", @morning_page %> |
  <%= link_to "Back to morning pages", morning_pages_path %>
</div>

app/views/morning_pages/index.html.erb
<p style="color: green"><%= notice %></p>

<%= render "form", morning_page: @morning_page %>

app/views/morning_pages/new.html.erb
<% content_for :title, "New morning page" %>

<h1>New morning page</h1>

<%= render "form", morning_page: @morning_page %>

<br>

<div>
  <%= link_to "Back to morning pages", morning_pages_path %>
</div>

app/views/morning_pages/show.html.erb
<p><%= notice %></p>

<%= render @morning_page %>

<div class="m-4 space-y-4 border-t-2 border-gray-300 pt-4">
  <div class="space-x-4">
    <%= link_to "Edit", edit_morning_page_path(@morning_page), class: "inline-block px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 transition-colors duration-300" %>
    <%= link_to "Archive", archive_morning_pages_path, class: "inline-block px-4 py-2 bg-gray-500 text-white rounded hover:bg-gray-600 transition-colors duration-300" %>
  </div>
  <%= button_to "Destroy this morning page", @morning_page, method: :delete, 
  class: "inline-block px-4 py-2 bg-red-500 text-white rounded hover:bg-red-600 transition-colors duration-300" %>
</div>